/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Pin_MOSI.h>
#include <Pin_MOSI_aliases.h>
#include <Pin_SCLK.h>
#include <Pin_SCLK_aliases.h>
#include <Pin_SS.h>
#include <Pin_SS_aliases.h>
#include <SPI_Clock.h>
#include <SPI.h>
#include <SPI_PVT.h>
#include <Pin_Button_Interrupt.h>
#include <Pin_Button_Interrupt_aliases.h>
#include <Pin_Button_0.h>
#include <Pin_Button_0_aliases.h>
#include <Pin_Button_1.h>
#include <Pin_Button_1_aliases.h>
#include <Pin_LED_Green.h>
#include <Pin_LED_Green_aliases.h>
#include <Pin_LED_Red.h>
#include <Pin_LED_Red_aliases.h>
#include <Pin_LED_Yellow.h>
#include <Pin_LED_Yellow_aliases.h>
#include <isr_spi.h>
#include <Pin_LED_Debug.h>
#include <Pin_LED_Debug_aliases.h>
#include <UART.h>
#include <UART_SPI_UART.h>
#include <UART_PINS.h>
#include <UART_SPI_UART_PVT.h>
#include <UART_PVT.h>
#include <UART_tx.h>
#include <UART_tx_aliases.h>
#include <UART_rx.h>
#include <UART_rx_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

